version: '3.8'

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - ftp

  ftp:
    image: fauria/vsftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./html:/home/vsftpd
    environment:
      - FTP_USER=admin
      - FTP_PASS=admin123
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
