version: '3.8'

services:
  phpmyadmin:
    build: .
    ports:
      - "8080:80" # Map port 8080 to access phpMyAdmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ABC13792588
      MYSQL_DATABASE: advance
      MYSQL_USER: Root
      MYSQL_PASSWORD: ABC13792588
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
